/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#9e0000",
        "primary-dark": "#7a0000",
        "primary-container": "#cc0000",
        "primary-light": "#ffdad4",
        "on-primary": "#ffffff",
        surface: "#f6faff",
        "surface-dim": "#d2dbe4",
        "surface-container": "#e6eff8",
        "surface-container-low": "#ecf5fe",
        "surface-container-high": "#e0e9f2",
        "on-surface": "#141d23",
        "on-surface-variant": "#5e3f3a",
        secondary: "#5f5e5e",
        "secondary-container": "#e2dfde",
        outline: "#926e69",
        "outline-variant": "#e8bdb6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        success: "#1a7a3c",
        "success-container": "#d4f5e0",
        warning: "#b45309",
        "warning-container": "#fef3c7",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)",
        "card-md": "0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06)",
        "card-lg": "0 10px 15px rgba(0,0,0,0.08), 0 4px 6px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
};
